version: '3'

networks:
  loki-net:

services:
  loki_instance1:
    image: grafana/loki:latest
    ports:
      - "3100:3001"
    networks:
      - loki-net

  # loki_instance2:
  #   image: grafana/loki:latest
  #   ports:
  #     - "3200:3002"
  #   networks:
  #     - loki-net

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://nginx_load_balancer
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki-net
